// Static, trusted content shared by the initial HTML and the recovered React view.
export const heroActions = `<div class="pp-start-actions"><button class="pp-start-primary" type="button" data-experience="start">Probar sin registro</button><button class="pp-start-secondary" type="button" data-experience="signup">Crear cuenta gratis</button></div><p class="pp-start-note">Sin cuenta: tus notas se guardan en este navegador. Con cuenta: puedes guardarlas en la nube.</p>`;

export const learnContent = `<section class="pp-learn" aria-label="Descubre PostisPop">
<div class="pp-section"><p class="pp-eyebrow">De la idea a la nota</p><h2>Empieza en tres pasos</h2><ol class="pp-cards"><li><h3>1. Escribe una idea</h3><p>Toca una nota vacía y escribe. Puedes volver a editarla cuando quieras.</p></li><li><h3>2. Dale su lugar</h3><p>Elige un color y arrastra una nota sobre otra para cambiar su posición.</p></li><li><h3>3. Conserva tu trabajo</h3><p>Comprueba el estado de guardado. Descarga una copia JSON para conservar tus notas fuera del navegador.</p></li></ol></div>
<div class="pp-section"><h2>Una pizarra para cada momento</h2><div class="pp-cards"><article><h3>Organiza tu día</h3><p>Separa lo urgente, lo que está en marcha y lo que ya has terminado.</p><a href="/organizador-visual-de-tareas.html">Organizar tareas</a></article><article><h3>Estudia con ideas claras</h3><p>Dedica cada nota a una pregunta y comprueba si puedes explicarla sin mirar tus apuntes.</p><a href="/notas-para-estudiar.html">Preparar una sesión de estudio</a></article><article><h3>Prepara tu próxima reunión</h3><p>Anota los temas, las decisiones y los siguientes pasos con una persona responsable.</p><a href="/pizarra-para-reuniones.html">Preparar una reunión</a></article></div></div>
<div class="pp-section"><h2>Tus notas, donde las necesitas</h2><div class="pp-cards"><article><h3>Sin registro</h3><p>Empieza gratis. Las notas se guardan en este navegador y dispositivo. Borrar los datos del navegador puede eliminarlas: exporta una copia.</p></article><article><h3>Con cuenta gratuita</h3><p>Guarda tus notas en tu cuenta y accede desde otros dispositivos al iniciar sesión. Las notas locales no se trasladan automáticamente.</p></article><article><h3>Trabajo compartido</h3><p>La gestión de invitaciones y enlaces está en revisión. No consideres una pizarra compartida hasta que la aplicación confirme el acceso.</p><a href="/pizarra-colaborativa.html">Preparar una pizarra colaborativa</a></article></div></div>
<div class="pp-section" id="planes"><h2>Gratis para empezar. Mejoras cuando las necesites.</h2><div class="pp-table-wrap"><table><caption>Opciones actuales de PostisPop</caption><thead><tr><th scope="col">Opción</th><th scope="col">Qué incluye</th><th scope="col">Precio</th></tr></thead><tbody><tr><th scope="row">Gratuito</th><td>Notas, colores, modo local y cuenta con guardado en la nube</td><td>0 €</td></tr><tr><th scope="row">Pack Rebel / Pack Minimal</th><td>Un estilo visual para tu pizarra</td><td>2,99 € cada pack</td></tr><tr><th scope="row">Reloj y recordatorios</th><td>Alarmas con PostisPop abierto; prueba de 30 días al registrarte</td><td>4,99 € · pago único</td></tr><tr><th scope="row">PostisPop Pro</th><td>Rebel, Minimal y reloj con alarmas</td><td>9,99 € · pago único</td></tr></tbody></table></div><p>La tienda confirma la disponibilidad antes de comprar. El pack Pro actual no es una suscripción.</p><a class="pp-start-secondary" href="/tienda/">Ver productos y disponibilidad</a></div>
<div class="pp-section"><h2>Preguntas frecuentes</h2><details><summary>¿Puedo usar PostisPop sin registrarme?</summary><p>Sí. Puedes escribir y editar notas en una pizarra local sin crear una cuenta.</p></details><details><summary>¿Dónde se guardan mis notas?</summary><p>Sin cuenta, en este navegador. Al iniciar sesión, las notas de tu cuenta se guardan en la nube. Exporta una copia antes de borrar los datos locales.</p></details><details><summary>¿Funcionan las alarmas con el navegador cerrado?</summary><p>No. Necesitan PostisPop abierto y el dispositivo activo. La suspensión del dispositivo puede retrasar los avisos.</p></details><details><summary>¿Se cobra automáticamente al terminar la prueba del reloj?</summary><p>No. La prueba dura 30 días y no requiere tarjeta. Después decides si compras el reloj.</p></details></div>
<div class="pp-section pp-final"><h2>Haz sitio a tu próxima idea</h2><p>Tu primera nota puede ser una tarea, una lista o algo que no quieras olvidar.</p><button class="pp-start-primary" type="button" data-experience="start">Escribir mi primera nota</button></div>
<nav class="pp-guide-links" aria-label="Guías de uso"><a href="/bloc-de-notas-online.html">Bloc de notas online</a><a href="/pizarra-virtual.html">Pizarra virtual</a><a href="/notas-adhesivas-online.html">Notas adhesivas online</a><a href="/lluvia-de-ideas-online.html">Lluvia de ideas</a></nav>
<details class="pp-measurement"><summary>Medición de uso en este dispositivo</summary><p>Puedes activar contadores locales para consultar cómo utilizas PostisPop. No contienen el texto de tus notas, tu correo ni identificadores de cuenta; no se envían a un servidor.</p><label><input type="checkbox" data-experience-analytics> Activar contadores locales</label><button type="button" data-experience="metrics">Descargar mis contadores</button></details>
</section>`;
