// Informational promotion only: no checkout or reward grants.
const banner=document.createElement('aside');
banner.className='pp-launch-promo';
banner.setAttribute('aria-label','Promoción de estreno');
banner.innerHTML='<div class="pp-promo-copy"><span class="pp-promo-label">Ruleta gratuita del sábado</span><h2>Consigue premios para tus ideas y tus juegos.</h2><p>Una tirada gratuita cada sábado. Descubre las tarjetas y los próximos premios.</p></div><div class="pp-promo-brands"><span><img class="prize-logo-amazon" src="/assets/prize-brands/amazon.ico" alt="Amazon" width="76" height="38"></span><span><img class="prize-logo-google-play" src="/assets/prize-brands/google-play.svg" alt="Google Play" width="76" height="38"></span><span><img class="prize-logo-apple" src="/assets/prize-brands/apple.svg" alt="Apple" width="76" height="38"></span><span><img class="prize-logo-xbox" src="/assets/prize-brands/xbox.svg" alt="Xbox" width="76" height="38"></span><span><img class="prize-logo-playstation" src="/assets/prize-brands/playstation.png" alt="PlayStation" width="76" height="38"></span><span><img class="prize-logo-fortnite" src="/assets/prize-brands/fortnite.png" alt="Fortnite" width="76" height="38"></span></div><div class="pp-promo-action"><a href="/premios.html">Ver premios</a><small>Requiere iniciar sesión. Sin compra. <a href="/terms.html" aria-label="Condiciones generales">Condiciones*</a></small></div>';
document.body.prepend(banner);
const measurement=document.createElement('script');measurement.type='module';measurement.src='/site-metrics.js';document.head.append(measurement);

async function updateOwnerMenu(){let link=document.getElementById('pp-owner-panel-link');if(link)link.remove();try{const response=await fetch('/api/designs/status');if(!response.ok)return;const data=await response.json();if(data.owner){link=document.createElement('a');link.id='pp-owner-panel-link';link.href='/propietario.html';link.textContent='Mi panel · Estadísticas';banner.querySelector('.pp-promo-action').append(link);}}catch{}}
measurement.addEventListener('load',updateOwnerMenu);window.addEventListener('postispop:session-change',updateOwnerMenu);window.addEventListener('focus',updateOwnerMenu);
