// Optional aggregate measurement. Never reads note text, input values, emails, IPs or tokens.
const KEY='pp:analytics-consent-v2',IDENTITY='pp:analytics-visitor-v2',SESSION='pp:analytics-session-v2';
const protectedChoice=()=>navigator.doNotTrack==='1'||navigator.globalPrivacyControl===true;
let enabled=false,visitor='',sessionId='',lastInput=Date.now(),lastTick=Date.now(),started=false;const depths=new Set();
const page=()=>location.pathname==='/'?'home':location.pathname.includes('atelier')?'shop':location.pathname.includes('premios')?'prizes':location.pathname.includes('terms')?'terms':'other';
const device=innerWidth<768?'mobile':innerWidth<1024?'tablet':'desktop';
let source='direct';try{if(document.referrer){const h=new URL(document.referrer).hostname;source=h===location.hostname?'internal':/google|bing|duckduckgo|yahoo/.test(h)?'search':/facebook|instagram|tiktok|youtube|twitter|t.co/.test(h)?'social':'other';}}catch{}
const networkFetch=window.fetch.bind(window);
function send(event,action='',seconds=0){if(!enabled||protectedChoice())return;networkFetch('https://htfyjefmviwlgmfqrwue.supabase.co/rest/v1/rpc/postispop_record_usage',{method:'POST',headers:{apikey:'sb_publishable_ox1LUYhmz57iSU7mPtGStg_-FZl-zQT','Content-Type':'application/json'},keepalive:true,body:JSON.stringify({p_event:{consent:'yes',visitor,session:sessionId,event,page:page(),device,source,action,seconds}})}).catch(()=>{});}
function start(){if(started||protectedChoice())return;try{let v=JSON.parse(localStorage.getItem(IDENTITY)||'null');if(!v||v.expires<Date.now())v={id:crypto.randomUUID(),expires:Date.now()+90*86400000};localStorage.setItem(IDENTITY,JSON.stringify(v));visitor=v.id;let s=JSON.parse(sessionStorage.getItem(SESSION)||'null');if(!s||Date.now()-s.last>30*60000)s={id:crypto.randomUUID(),last:Date.now()};s.last=Date.now();sessionStorage.setItem(SESSION,JSON.stringify(s));sessionId=s.id;enabled=true;started=true;lastTick=Date.now();send('page_view');}catch{enabled=false;}}
function choose(value){enabled=false;started=false;try{localStorage.setItem(KEY,value);if(value!=='yes'){localStorage.removeItem(IDENTITY);sessionStorage.removeItem(SESSION);}}catch{}if(value==='yes')start();document.getElementById('pp-analytics-choice')?.remove();}
function preferences(){document.getElementById('pp-analytics-choice')?.remove();const box=document.createElement('aside');box.id='pp-analytics-choice';box.setAttribute('aria-label','Preferencias de medición');box.style.cssText='position:fixed;bottom:16px;right:16px;max-width:min(420px,calc(100vw - 32px));background:#fff;color:#172033;padding:20px;border:1px solid #8792a5;border-radius:14px;z-index:9999;box-shadow:0 4px 20px #0002;font:15px/1.5 system-ui';const p=document.createElement('p');p.textContent='¿Nos permites medir visitas, clics, tiempo activo y uso de funciones para mejorar PostisPop? Se enviarán estadísticas a nuestro servidor, sin el contenido de tus notas. Es opcional.';box.append(p);for(const [label,value]of [['Aceptar medición','yes'],['Rechazar','no']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='padding:10px;margin:4px;border:1px solid #46566d;border-radius:6px;background:#fff;color:#172033;font:inherit;cursor:pointer';b.onclick=()=>choose(value);box.append(b);}const link=document.createElement('a');link.href='/terms.html';link.textContent='Información sobre la medición';link.style.cssText='display:block;color:#234c85';box.append(link);document.body.append(box);}
const settings=document.createElement('button');settings.type='button';settings.textContent='Preferencias de medición';settings.style.cssText='display:block;margin:20px auto;padding:8px;font:inherit';settings.onclick=preferences;document.body.append(settings);
try{const choice=localStorage.getItem(KEY);if(choice==='yes')start();else if(choice===null&&!protectedChoice())preferences();}catch{}
for(const event of ['pointerdown','keydown','scroll'])window.addEventListener(event,()=>{lastInput=Date.now();},{passive:true});
setInterval(()=>{const now=Date.now();if(enabled&&document.visibilityState==='visible'&&now-lastInput<60000){send('active_time','',Math.min(30,Math.floor((now-lastTick)/1000)));try{sessionStorage.setItem(SESSION,JSON.stringify({id:sessionId,last:now}));}catch{}}lastTick=now;},30000);
document.addEventListener('click',event=>{const target=event.target.closest('button,a');if(!target||target.closest('#pp-analytics-choice'))return;let action='button';const id=target.id||'';if(/^at-[a-z-]{1,45}$/.test(id))action=id;else if(target.matches('a')){try{const u=new URL(target.href);action=u.origin!==location.origin?'external_link':u.pathname.includes('premios')?'open_prizes':u.pathname.includes('atelier')?'open_shop':u.pathname.includes('terms')?'open_terms':u.pathname==='/'?'open_home':'internal_link';}catch{action='link';}}send('click',action);});
window.addEventListener('scroll',()=>{const size=document.documentElement.scrollHeight-innerHeight;if(size<=0)return;const progress=Math.min(100,Math.round(scrollY/size*100));for(const threshold of [25,50,75,100])if(progress>=threshold&&!depths.has(threshold)){depths.add(threshold);send('scroll','depth_'+threshold);}},{passive:true});
window.addEventListener('pagehide',()=>send('page_exit'));
window.addEventListener('error',()=>send('error','javascript'));
window.addEventListener('storage',event=>{if(event.key===KEY){enabled=false;started=false;if(event.newValue==='yes')start();}});
const appFetch=window.fetch.bind(window);window.fetch=async function(input,init){const response=await appFetch(input,init);try{const raw=typeof input==='string'?input:input?.url;const u=new URL(raw,location.href);const method=(init?.method||input?.method||'GET').toUpperCase();if(enabled&&u.origin===location.origin&&u.pathname.startsWith('/api/')&&response.ok&&method!=='GET'){const route=u.pathname;let event='';if(/notes/.test(route))event=method==='POST'?'note_create':method==='PATCH'||method==='PUT'?'note_edit':'';else if(/boards/.test(route)&&method==='POST')event='board_create';else if(/shares/.test(route))event='share';else if(/auth|signup/.test(route))event='account';if(event)send(event);}}catch{}return response;};
