const {browserOptions}=require('./browser-options.cjs');
const {chromium}=require('playwright');
const fs=require('node:fs/promises');const path=require('node:path');
(async()=>{
 const root=path.resolve(__dirname,'../android/app/src/main/assets/www');
 const host=await fs.readFile(path.resolve(__dirname,'../android/app/src/main/java/com/postispop/android/MainActivity.java'),'utf8');
 const policy=host.match(/headers\.put\("Content-Security-Policy", "([^"]+)"\)/)?.[1];
 if(!policy)throw Error('Native content security policy missing');
 const b=await chromium.launch(browserOptions({args:['--no-sandbox']}));
 const c=await b.newContext({serviceWorkers:'block',locale:'es-ES',viewport:{width:412,height:850}});const p=await c.newPage();
 const errors=[];p.on('pageerror',e=>errors.push(e.message));
 p.on('console',message=>{if(message.type()==='error'&&/violates.*Content Security Policy|Refused to.*(?:script|style|font|connect)/i.test(message.text()))errors.push(message.text());});
 await c.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.hostname!=='postispop.com') return route.abort('internetdisconnected');
  let name=decodeURIComponent(u.pathname);if(name.endsWith('/'))name+='index.html';
  const file=path.join(root,name);const ext=path.extname(file);
  const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.avif':'image/avif'};
  try {await route.fulfill({status:200,contentType:types[ext]||'application/octet-stream',headers:{'Content-Security-Policy':policy,'X-Content-Type-Options':'nosniff'},body:await fs.readFile(file)});}catch{await route.fulfill({status:404,body:'not bundled'});}
 });
 await p.goto('https://postispop.com/');
 await p.waitForSelector('.sticky-note:not([disabled])',{timeout:30000});
 console.log('Local UI ready:',await p.locator('.sticky-note').count(),'notes');
 await p.locator('.sticky-note').first().click();
 await p.locator('textarea').fill('Nota Android local sin Internet');
 await p.getByRole('button',{name:'Más opciones de la nota',exact:true}).click();
 await p.waitForSelector('.pp-attachments');
 await p.locator('.pp-file-action input').setInputFiles({name:'prueba.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 PostisPop')});
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===1);
 await p.locator('.pp-link-action').click();
 await p.locator('.pp-link-form input').fill('https://example.com/idea');
 await p.locator('.pp-link-form button[type=submit]').click();
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===2);
 await p.waitForFunction(()=>JSON.parse(localStorage.getItem('postispop-guest-board-v1'))?.notes[0]?.text==='Nota Android local sin Internet');
 await p.reload();
 await p.waitForSelector('.sticky-note:not([disabled])');
 if (!(await p.locator('.sticky-note').first().innerText()).includes('Nota Android local sin Internet')) throw Error('Local note lost on reload');
 await p.locator('.sticky-note').first().click();
 await p.getByRole('button',{name:'Más opciones de la nota',exact:true}).click();
 await p.waitForSelector('.pp-attachments');
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===2);
 await p.goto('https://postispop.com/atelier.html');
 await p.waitForSelector('.payment-options');
 if(await p.locator('.payment-option button').count()!==3)throw Error('Missing three disabled premium options');
 for(const button of await p.locator('.payment-option button').all())if(await button.isEnabled())throw Error('Payments unexpectedly enabled');
 await p.goto('https://postispop.com/descargas/');
 if(await p.locator('h1').innerText()!=='Descargas')throw Error('Missing bundled downloads page');
 if(await p.locator('[data-platform]').count()!==7)throw Error('Missing download platform information');
 await p.getByRole('link',{name:'Ver cómo instalar',exact:true}).click();
 if(await p.locator('h1').innerText()!=='Tus ideas, también en tu dispositivo.')throw Error('Missing bundled installation guide');
 if(await p.locator('#install').isVisible())throw Error('Install button shown without install support');
 console.log('PASS: bundled UI startup, offline note and attachments reload, three inactive Premium prices and installation pages');
 if(errors.length)throw Error(errors.join('\n'));
 await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
