const {chromium}=require('playwright');
const fs=require('node:fs/promises');const path=require('node:path');
(async()=>{
 const root=path.resolve(__dirname,'../android/app/src/main/assets/www');
 const b=await chromium.launch({headless:true,executablePath:process.env.POSTISPOP_CHROME,args:['--no-sandbox']});
 const c=await b.newContext({serviceWorkers:'block',locale:'es-ES',viewport:{width:412,height:850}});const p=await c.newPage();
 const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.hostname!=='postispop.com') return route.abort('internetdisconnected');
  let name=decodeURIComponent(u.pathname);if(name.endsWith('/'))name+='index.html';
  const file=path.join(root,name);const ext=path.extname(file);
  const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.avif':'image/avif'};
  try {await route.fulfill({status:200,contentType:types[ext]||'application/octet-stream',body:await fs.readFile(file)});}catch{await route.fulfill({status:404,body:'not bundled'});}
 });
 await p.goto('https://postispop.com/');
 await p.waitForSelector('.sticky-note:not([disabled])',{timeout:30000});
 console.log('Local UI ready:',await p.locator('.sticky-note').count(),'notes');
 await p.locator('.sticky-note').first().click();
 await p.locator('textarea').fill('Nota Android local sin Internet');
 await p.waitForSelector('.pp-attachments');
 await p.locator('.pp-file-action input').setInputFiles({name:'prueba.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 PostisPop')});
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===1);
 await p.locator('.pp-link-action').click();
 await p.locator('.pp-link-form input').fill('https://example.com/idea');
 await p.locator('.pp-link-form button[type=submit]').click();
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===2);
 await p.waitForFunction(()=>JSON.parse(localStorage.getItem('postispop-guest-board-v1'))?.notes[0]?.text==='Nota Android local sin Internet');
 await p.reload();
 await p.waitForSelector('.sticky-note:not([disabled])');
 if (!(await p.locator('.sticky-note').first().innerText()).includes('Nota Android local sin Internet')) throw Error('Local note lost on reload');
 await p.locator('.sticky-note').first().click();
 await p.waitForFunction(()=>document.querySelectorAll('.pp-attachment-card').length===2);
 await p.goto('https://postispop.com/tienda/');
 await p.waitForSelector('[data-product-card]');
 if(await p.locator('[data-product-card]').count()!==4)throw Error('Missing bundled products');
 await p.goto('https://postispop.com/tienda/buscar/');
 await p.locator('#site-search').fill('reloj');
 await p.locator('button[type=submit]').click();
 await p.waitForFunction(()=>document.querySelector('[data-search-status]')?.textContent.includes('resultado'),null,{timeout:10000});
 await p.goto('https://postispop.com/descargas/');
 if(await p.locator('h1').innerText()!=='Descargas')throw Error('Missing bundled downloads page');
 if(await p.locator('[data-platform]').count()!==7)throw Error('Missing download platform information');
 await p.getByRole('link',{name:'Ver cómo instalar',exact:true}).click();
 if(await p.locator('h1').innerText()!=='Tus ideas, también en tu dispositivo.')throw Error('Missing bundled installation guide');
 if(await p.locator('#install').isVisible())throw Error('Install button shown without install support');
 console.log('PASS: bundled UI startup, offline note and attachments reload, four local products, offline search and installation pages');
 if(errors.length)throw Error(errors.join('\n'));
 await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
