const {test}=require('node:test'),assert=require('node:assert/strict');
const load=()=>import('../offline-sync.js');
const storage=()=>{const m=new Map();return{get length(){return m.size},key:i=>[...m.keys()][i]??null,getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),map:m}};
const board=()=>({id:'board-a',notes:[{id:'note-a',revision:1,text:'Original',marks:[],paper:0,doodle:'',image:null}],order:['note-a']});
async function setup(){const {createOfflineStore}=await load(),disk=storage();let id=0;const db=createOfflineStore(disk,()=>100,()=>String(++id));db.remember('A','board/board-a',board());return{db,disk,createOfflineStore};}
test('Queued account edits survive reload in order, without touching the server snapshot',async()=>{const {db,disk,createOfflineStore}=await setup();db.enqueue('A','note/note-a',{text:'First',revision:1});db.enqueue('A','note/note-a/paper',{paper:5,revision:2});const restarted=createOfflineStore(disk);assert.equal(restarted.pending('A').length,2);const note=restarted.cached('A','board/board-a').notes[0];assert.equal(note.text,'First');assert.equal(note.paper,5);assert.equal(note.revision,3);assert.equal(JSON.parse(disk.map.get('postispop:offline:v1:A:cache:board/board-a')).notes[0].text,'Original');});
test('One account cannot read, acknowledge or queue against another account cache',async()=>{const {db}=await setup();db.enqueue('A','note/note-a',{text:'Private A',revision:1});assert.equal(db.cached('B','board/board-a'),null);assert.deepEqual(db.pending('B'),[]);assert.throws(()=>db.enqueue('B','note/note-a',{text:'Wrong account',revision:1}),/NOT_CACHED/);assert.throws(()=>db.resolve('B',db.pending('A')[0].id,'server'),/NOT_FOUND/);});
test('Conflicting local versions are retained and server choice archives all dependent note changes',async()=>{const {db}=await setup();db.enqueue('A','note/note-a',{text:'Local draft',revision:1});db.enqueue('A','note/note-a/paper',{paper:3,revision:2});const op=db.pending('A')[0];db.conflict('A',op,{...board().notes[0],text:'Other device',revision:2});assert.equal(db.cached('A','board/board-a').notes[0].text,'Local draft');db.resolve('A',op.id,'server');assert.equal(db.pending('A').length,0);assert.equal(db.recovery('A')[0].operations.length,2);assert.equal(db.cached('A','board/board-a').notes[0].text,'Other device');});
test('Choosing local rebases ordered revisions only after explicit conflict resolution',async()=>{const {db}=await setup();db.enqueue('A','note/note-a',{text:'Local',revision:1});db.enqueue('A','note/note-a/paper',{paper:3,revision:2});const op=db.pending('A')[0];db.conflict('A',op,{...board().notes[0],revision:7});db.resolve('A',op.id,'local');assert.deepEqual(db.pending('A').map(o=>o.body.revision),[7,8]);});
test('Storage quota failure does not report a successful local save',async()=>{const {db,disk}=await setup();disk.setItem=()=>{throw Error('QuotaExceededError')};assert.throws(()=>db.enqueue('A','note/note-a',{text:'Do not lose',revision:1}),/OFFLINE_STORAGE_FULL/);assert.equal(db.pending('A').length,0);});
test('Protecting a note purges old styles, recovery and shared device caches for every account',async()=>{const {db,disk}=await setup();db.remember('B','board/board-a',board());db.cacheStyles('A',[{note_id:'note-a',drawing:{secret:'drawing'}}]);db.enqueue('A','note/note-a',{text:'Sensitive',revision:1});const op=db.pending('A')[0];db.conflict('A',op,{...board().notes[0],revision:2});db.resolve('A',op.id,'server');assert.equal(db.noteHistory('note-a').recovery,1);db.sanitizeProtected({...board().notes[0],text:'Nota protegida',protectedEnvelope:{ciphertext:'encrypted'},revision:3});assert.equal(db.recovery('A').length,0);assert.equal(db.projectStyles('A').length,0);assert.equal(db.cached('B','board/board-a').notes[0].text,'Nota protegida');assert.ok(![...disk.map.values()].join('').includes('Sensitive'));});
test('Protection refuses to delete pending changes, including another account',async()=>{const {db}=await setup();db.enqueue('A','note/note-a',{text:'Pending',revision:1});assert.throws(()=>db.sanitizeProtected({...board().notes[0],protectedEnvelope:{ciphertext:'x'}}),/SYNC_PENDING/);assert.equal(db.pending('A')[0].body.text,'Pending');});
test('Only ciphertext may be queued for a protected note',async()=>{const {db}=await setup();db.sanitizeProtected({...board().notes[0],text:'Nota protegida',protectedEnvelope:{ciphertext:'first'}});assert.throws(()=>db.enqueue('A','note/note-a',{text:'Plaintext',revision:1}),/PROTECTED_NOTE/);db.enqueue('A','note/note-a/protected-save',{revision:1,protectedEnvelope:{ciphertext:'second'}});assert.equal(db.pending('A')[0].after.text,'Nota protegida');assert.equal(db.pending('A')[0].body.protectedEnvelope.ciphertext,'second');});
test('A lost response can be acknowledged only when revision and changed fields match',async()=>{const {db}=await setup(),{sameMutation}=await load();db.enqueue('A','note/note-a',{text:'Saved',revision:1});const op=db.pending('A')[0];assert.equal(sameMutation(op,{...op.after}),true);assert.equal(sameMutation(op,{...op.after,revision:3}),false);assert.equal(sameMutation(op,{...op.after,text:'Other'}),false);});
