const {chromium}=require('playwright');const {createServer}=require('node:http');const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
 const root=path.resolve('_site');const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff':'font/woff','.woff2':'font/woff2'};
 const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');let name=url.pathname;if(name.endsWith('/'))name+='index.html';try{const data=await fs.readFile(path.join(root,name));res.writeHead(200,{'Content-Type':types[path.extname(name)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true});
 try{const context=await browser.newContext({locale:'es-ES'}),page=await context.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/`);await page.waitForSelector('#pp-board-tools');await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);
 await page.locator('.sticky-note:not([disabled])').first().click();await page.locator('textarea').fill('Persistencia PWA sin conexión');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('postispop-guest-board-v1'))?.notes[0]?.text==='Persistencia PWA sin conexión');
 const cached=await page.evaluate(async()=>{const lists=await Promise.all((await caches.keys()).map(async k=>(await(await caches.open(k)).keys()).map(r=>r.url)));return lists.flat();});assert.ok(cached.length>15);assert.ok(cached.every(u=>!u.includes('/api/')&&!u.includes('supabase.co')&&!u.includes('/compartir/')));
 await context.setOffline(true);await page.reload();await page.waitForSelector('.sticky-note:not([disabled])');assert.match(await page.locator('.sticky-note').first().innerText(),/Persistencia PWA sin conexión/);console.log(`PASS PWA: ${cached.length} public assets cached, no API/session data, offline reload preserved note.`);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
})().catch(e=>{console.error(e);process.exitCode=1;});
