import { TEMPLATES, createBackup, parseBackup, filterNotes, templateNotes, metadata } from './board-core.js';
import { api, dialog, escape, notice, errorMessage, download } from './ui.js';
import { track } from './analytics.js';
let board=null,actor=null, toolbar, query='',paper='',tag='',archived=false;
window.addEventListener('postispop:board',e=>{board=e.detail.board;actor=e.detail.actor;renderFilters();if(board.notes.some(n=>n.text?.trim()))track('first_note_created',true);track('first_board_created',true);});
function renderFilters() {
  if(!board||!toolbar)return;
  const visible=filterNotes(board.notes,{query,paper,tag,archived});
  const ids=new Set(visible.map(n=>n.id));
  document.querySelectorAll('[data-note-id]').forEach(node=>{const note=board.notes.find(n=>n.id===node.dataset.noteId);if(!note)return;node.closest('.note-cell').hidden=!ids.has(note.id);node.closest('.note-cell').style.order=note.metadata?.pinned?'-1':'';node.classList.toggle('pp-pinned',Boolean(note.metadata?.pinned));});
  document.querySelectorAll('.note-cell:not(:has([data-note-id]))').forEach(cell=>{cell.hidden=Boolean(query||paper||tag||archived);});
  const count=toolbar.querySelector('[data-results]');count.textContent=`${visible.length} notas${query||paper||tag||archived?' en este filtro':''}`;
}
function requireBoard(){if(!board)throw Error('NOT_FOUND');return board;}
function selectBoard(id){localStorage.setItem('pp:last-board',id);location.assign('/');}
export function mountTools() {
  if(document.getElementById('pp-board-tools'))return;
  const frame=document.querySelector('.board-frame');if(!frame)return;
  frame.id='mi-pizarra';toolbar=document.createElement('section');toolbar.id='pp-board-tools';toolbar.setAttribute('aria-label','Herramientas de la pizarra');
  toolbar.innerHTML=`<div class="pp-tool-row"><label>Buscar notas<input type="search" placeholder="Texto o etiqueta" aria-keyshortcuts="Control+K Meta+K" data-search></label><label>Color<select data-color><option value="">Todos</option>${['Amarillo','Rosa','Verde','Azul','Lila','Blanco'].map((c,i)=>`<option value="${i}">${c}</option>`).join('')}</select></label><label>Etiqueta<input data-tag placeholder="Etiqueta exacta"></label><label class="pp-inline-check"><input type="checkbox" data-archive> Archivadas</label></div><div class="pp-tool-row">${[['templates','Plantillas'],['backup','Exportar / Copias'],['share','Compartir'],['organize','Organizar notas'],['shortcuts','Atajos'],['theme','Claro / Oscuro']].map(([a,t])=>`<button type="button" data-tool="${a}">${t}</button>`).join('')}<span data-results role="status"></span></div><p id="pp-save-status" role="status" aria-live="polite">Cargando pizarra…</p>`;
  frame.before(toolbar);
  toolbar.querySelector('[data-search]').oninput=e=>{query=e.target.value;renderFilters();};toolbar.querySelector('[data-color]').onchange=e=>{paper=e.target.value;renderFilters();};toolbar.querySelector('[data-tag]').oninput=e=>{tag=e.target.value.trim();renderFilters();};toolbar.querySelector('[data-archive]').onchange=e=>{archived=e.target.checked;renderFilters();};
  toolbar.addEventListener('click',async e=>{const action=e.target.closest('[data-tool]')?.dataset.tool;if(!action)return;try{requireBoard();if(action==='theme'){const value=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=value;localStorage.setItem('pp:appearance',value);}if(action==='templates')templates();if(action==='backup')backups();if(action==='share')await sharing();if(action==='organize')organize();if(action==='shortcuts')dialog('Atajos de teclado','<p><kbd>Ctrl/⌘ K</kbd>: buscar notas.<br><kbd>Alt N</kbd>: abrir la primera nota vacía.<br><kbd>Esc</kbd>: cerrar un diálogo.<br><kbd>Tab</kbd> y <kbd>Mayús Tab</kbd>: recorrer controles.</p>');}catch(err){notice(errorMessage(err));}});
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();toolbar.querySelector('[data-search]').focus();}if(e.altKey&&e.key.toLowerCase()==='n'){e.preventDefault();const n=board?.notes.find(n=>!n.text&&!n.metadata?.archived);if(n)document.querySelector(`[data-note-id="${CSS.escape(n.id)}"]`)?.click();}});
  renderFilters();
}
function templates(){
  const d=dialog('Empieza con una plantilla',`<p>Se añaden a espacios vacíos. Tus notas actuales se conservan.</p><div class="pp-template-grid">${TEMPLATES.map(t=>`<button data-template="${t.id}"><strong>${t.title}</strong><small>${t.notes.length} notas</small></button>`).join('')}</div><p role="status"></p>`);
  d.addEventListener('click',async e=>{const b=e.target.closest('[data-template]');if(!b)return;b.disabled=true;try{const data=templateNotes(b.dataset.template);await api(`board/${board.id}/import`,{notes:data.notes});d.close();notice('Plantilla añadida.');await refresh();}catch(err){d.querySelector('[role=status]').textContent=errorMessage(err);}finally{b.disabled=false;}});
}
async function refresh(){const data=await api('board/'+board.id);board=data;window.dispatchEvent(new CustomEvent('postispop:board',{detail:{board,actor}}));}
function organize(){
  const d=dialog('Etiquetas, notas fijadas y archivo',`<p>Archivar oculta una nota sin eliminarla. Usa el filtro «Archivadas» para recuperarla.</p><form><label>Nota<select name="note">${board.notes.map((n,i)=>`<option value="${escape(n.id)}">${i+1}. ${escape(n.text.slice(0,65)||'Nota vacía')}</option>`).join('')}</select></label><label>Etiquetas (separadas por comas)<input name="tags" maxlength="330"></label><label class="pp-inline-check"><input type="checkbox" name="pinned"> Fijar al principio</label><label class="pp-inline-check"><input type="checkbox" name="archived"> Archivar</label><button type="submit">Guardar organización</button><p role="status"></p></form>`);
  const form=d.querySelector('form'),select=form.elements.namedItem('note');const load=()=>{const m=metadata(board.notes.find(n=>n.id===select.value).metadata);form.elements.namedItem('tags').value=m.tags.join(', ');form.elements.namedItem('pinned').checked=m.pinned;form.elements.namedItem('archived').checked=m.archived;};select.onchange=load;load();
  form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const n=board.notes.find(n=>n.id===select.value);await api('note/'+n.id+'/metadata',{revision:n.revision,metadata:metadata({tags:form.elements.namedItem('tags').value.split(','),pinned:form.elements.namedItem('pinned').checked,archived:form.elements.namedItem('archived').checked})});await refresh();d.close();notice('Organización guardada.');}catch(err){form.querySelector('[role=status]').textContent=errorMessage(err);}finally{submit.disabled=false;}};
}
function backups(){
  const d=dialog('Exportar y conservar tus notas',`<p>JSON conserva texto, colores, trazos y organización. Los archivos adjuntos locales se descargan desde cada nota y no se incluyen en esta copia.</p><div class="pp-tool-row"><button data-export="json">Descargar JSON</button><button data-export="png">Exportar PNG</button><button data-export="pdf">Imprimir / Guardar PDF</button><button data-duplicate>Duplicar pizarra</button></div><label>Importar copia JSON<input type="file" accept=".json,application/json" data-import></label><p>La importación crea otra pizarra: no reemplaza tus notas.</p><p role="status"></p>`);
  d.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
    if(b.dataset.export==='json'){download('postispop-copia.json',JSON.stringify(createBackup(board),null,2));track('export');}
    if(b.dataset.export==='png'){await exportPng();track('export');}
    if(b.dataset.export==='pdf'){await exportPrint();track('export');}
    if(b.hasAttribute('data-duplicate')){b.disabled=true;const copy=parseBackup(createBackup(board));copy.title+=' (copia)';const next=await api('tools/create',copy);selectBoard(next.id);}
  }catch(err){d.querySelector('[role=status]').textContent=errorMessage(err);b.disabled=false;}});
  d.querySelector('[data-import]').onchange=async e=>{const file=e.target.files[0];if(!file)return;const status=d.querySelector('[role=status]');try{if(file.size>2000000)throw Error('BACKUP_TOO_LARGE');const copy=parseBackup(await file.text());status.textContent=`Copia válida: ${copy.notes.length} notas. `;const confirm=document.createElement('button');confirm.textContent='Crear pizarra desde esta copia';confirm.onclick=async()=>{confirm.disabled=true;try{const next=await api('tools/create',copy);selectBoard(next.id);}catch(err){status.textContent=errorMessage(err);}};status.append(confirm);}catch(err){status.textContent=errorMessage(err);}};
}
const colors=['#ffec86','#ffc9dd','#d5ecc7','#cce6fb','#e2d7fa','#fff'];
function wrapText(ctx,text,width){const lines=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(' ')){if(ctx.measureText(line+word).width>width&&line){lines.push(line);line='';}for(const ch of word){if(ctx.measureText(line+ch).width>width){lines.push(line);line='';}line+=ch;}line+=' ';}lines.push(line.trimEnd());}return lines;}
async function exportPng(){
  const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=1200;ctx.font='20px system-ui';
  const ordered=board.order.map(id=>board.notes.find(n=>n.id===id)).filter(Boolean),lines=ordered.map(n=>wrapText(ctx,n.text,330));
  const heights=[];for(let i=0;i<ordered.length;i+=3)heights.push(Math.max(180,...lines.slice(i,i+3).map(l=>l.length*27+75)));
  canvas.height=120+heights.reduce((a,b)=>a+b+20,0);if(canvas.height>16000)throw Error('BACKUP_TOO_LARGE');
  ctx.fillStyle='#f5f1e8';ctx.fillRect(0,0,1200,canvas.height);ctx.fillStyle='#20283a';ctx.font='bold 32px system-ui';ctx.fillText(board.title||'Mi pizarra',30,55);ctx.font='16px system-ui';ctx.fillText('Exportación de texto y colores · Los adjuntos y dibujos se conservan por separado.',30,85);
  let y=110;ordered.forEach((n,i)=>{if(i&&i%3===0)y+=heights[Math.floor(i/3)-1]+20;const x=25+(i%3)*390;ctx.fillStyle=colors[n.paper]||colors[0];ctx.fillRect(x,y,365,heights[Math.floor(i/3)]);ctx.fillStyle='#20283a';ctx.font='bold 16px system-ui';ctx.fillText(`Nota ${i+1}`,x+16,y+28);ctx.font='20px system-ui';lines[i].forEach((line,j)=>ctx.fillText(line,x+16,y+62+j*27));});
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('EXPORT_FAILED');download('postispop-pizarra.png',blob);
}
async function exportPrint(){
  const frame=document.createElement('iframe');frame.title='Copia para imprimir';frame.className='pp-print-frame';document.body.append(frame);
  const doc=frame.contentDocument;doc.open();doc.write(`<!doctype html><html lang="es"><head><title>${escape(board.title)}</title><style>body{font:14pt system-ui;color:#182033}article{padding:16px;margin:12px 0;border:1px solid #bbb;break-inside:avoid}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}@page{size:A4;margin:15mm}</style></head><body><h1>${escape(board.title)}</h1><p>Texto y colores. Los archivos adjuntos y dibujos se exportan por separado.</p>${board.order.map(id=>board.notes.find(n=>n.id===id)).filter(Boolean).map((n,i)=>`<article style="border-left:12px solid ${colors[n.paper]||colors[0]}"><h2>Nota ${i+1}</h2><pre>${escape(n.text)}</pre></article>`).join('')}</body></html>`);doc.close();frame.contentWindow.focus();frame.contentWindow.print();setTimeout(()=>frame.remove(),60000);
}
async function sharing(){
  if(!actor?.registered||board.id.startsWith('guest-board')){const d=dialog('Guarda y comparte desde tu cuenta','<p>Esta pizarra está solo en este dispositivo. Descarga una copia JSON, inicia sesión e impórtala para compartirla.</p><button data-signin>Crear cuenta gratis / Iniciar sesión</button>');d.querySelector('[data-signin]').onclick=()=>{d.close();document.querySelector('.header-auth-signup,.header-auth-login')?.click();};return;}
  const d=dialog('Compartir esta pizarra',`<p>Solo el propietario crea y revoca enlaces. Los enlaces de edición exigen iniciar sesión; los de lectura permiten ver la pizarra sin cuenta.</p><form><label>Acceso<select name="role"><option value="viewer">Solo lectura</option><option value="editor">Editable, con cuenta</option></select></label><label>Correo de la persona invitada (opcional)<input name="email" type="email" placeholder="Restringir a una cuenta concreta"></label><label>Caduca en<select name="days"><option value="1">1 día</option><option value="7" selected>7 días</option><option value="30">30 días</option></select></label><button type="submit">Crear enlace</button><p role="status"></p></form><section data-links></section>`);
  const list=async()=>{const result=await api('tools/shares',{board_id:board.id,action:'list'});d.querySelector('[data-links]').innerHTML='<h3>Enlaces activos</h3>'+result.shares.map(s=>`<p>${s.role==='viewer'?'Lectura':'Edición'} · caduca ${escape(new Date(s.expires_at).toLocaleDateString('es-ES'))} <button data-revoke="${s.id}">Revocar</button></p>`).join('');};
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]');b.disabled=true;try{const values=new FormData(f);const r=await api('tools/shares',{action:'create',board_id:board.id,role:values.get('role'),email:values.get('email'),days:Number(values.get('days'))});const url=location.origin+'/compartir/#'+r.token;const status=f.querySelector('[role=status]');status.innerHTML='<label>Enlace creado<input readonly aria-label="Enlace para compartir"></label><button type="button" data-copy>Copiar enlace</button><small>Comparte este enlace tú mismo. No se ha enviado ningún correo.</small>';status.querySelector('input').value=url;status.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url);notice('Enlace copiado.');}catch{status.querySelector('input').select();}};track('board_shared');await list();}catch(err){f.querySelector('[role=status]').textContent=errorMessage(err);}finally{b.disabled=false;}};
  d.addEventListener('click',async e=>{const b=e.target.closest('[data-revoke]');if(!b)return;b.disabled=true;try{await api('tools/shares',{action:'revoke',board_id:board.id,id:b.dataset.revoke});await list();notice('Acceso revocado.');}catch(err){notice(errorMessage(err));b.disabled=false;}});
  try{await list();}catch(err){d.querySelector('[data-links]').textContent=errorMessage(err);}
}
// Route the existing share affordances into the same tested permissions flow.
document.addEventListener('click',e=>{if(e.target.closest('.header-share,.group-button')){e.preventDefault();e.stopImmediatePropagation();sharing().catch(err=>notice(errorMessage(err)));}},true);
