// Writes a reviewable migration; never connects to a live database.
import fs from 'node:fs';
import {designs,packs} from '../design-catalog.js';
const quote=value=>"'"+String(value).replaceAll("'","''")+"'";
if(new Set(designs.map(d=>d.id)).size!==designs.length)throw Error('Duplicate design IDs');
const values=designs.map(d=>`(${[d.id,d.title,d.category,d.tier,d.pack||packs.find(p=>p.designIds.includes(d.id))?.id||d.category.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-'),d.paper||'plain'].map(quote).join(',')})`);
const memberships=packs.flatMap(p=>p.designIds.map(id=>`(${quote(p.id)},${quote(id)})`));
const sql=`-- Generated by scripts/seed-designs.mjs. ${designs.length} catalog entries; this is not evidence all artwork is complete.\n-- Apply after designs.sql. No prices or licenses are created. Existing unlocks are retained.\nbegin;\ninsert into public.postispop_designs(id,title,category,tier,pack,default_paper) values\n${values.join(',\n')}\non conflict(id) do update set title=excluded.title,category=excluded.category,tier=excluded.tier,pack=excluded.pack,default_paper=excluded.default_paper;\ninsert into public.postispop_design_pack_entries(pack_id,design_id) values\n${memberships.join(',\n')}\non conflict do nothing;\ncommit;\n`;
fs.writeFileSync(new URL('../database/design-catalog-seed.sql',import.meta.url),sql);
console.log(`Generated ${designs.length} catalog rows; ${designs.filter(d=>d.tier==='reward').length} reward designs.`);
